version: '3'
services:
  frontend:
    build:
      context: ./my-app
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount actual certs from host to container
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
